---
title: "Report"
author: "Elizabeth Serrano"
date: "2022-11-26"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse) #contains multiple tidy packages 
library(dplyr) #used for data manipulation 
```

```{r - Cleaning up the Raw Data}
FishFraud <- read.csv("Fish Fraud Data CSV.csv") #loaded the csv file of the raw data into r 


TidyFishFraud <- select(FishFraud, -Fraud.map.category, -Notes, -repeat., -Species.Geographic.Range, -Amount.of.processing, -Website, -Reference, -In.fraud.map., -In.endnote., -Fraud.Map.ID., -Potentially.Farmed., -farmed.n, -X, -X.1, -X.2, -X.3, -X.4, -X.5, -X.6, -X.7, -X.8) #i removed these columns as i determined that they were either irrelevant to what I wanted to asnwer, or there wasnt enough data in these columns to do anything with it 

TidyFishFraud <- filter(
  TidyFishFraud, 
  !is.na(Study.number)
) #here I am removing all the rows that contain an NA under the study.number column. 

glimpse(TidyFishFraud)


```
```{r what places where the fish mostly retrieved from?}
#I want to know where most of the fish was sampled from. So I am going to need to create a data frame that takes the studies columns and the locations of the purchased fish 
FraudLocation <-select(TidyFishFraud, Study.number, Study.authors...year, Sampling.Area..where.retail.fish.purchased.)
#This is data frame showing all the studies and all the places the fish from those studies were bought from (location) 
# Since most of this sea food was sampled within the US, I am going to try to standardize these entries to show the locations (states within the US) where the seafood came from. 

#Purchased within US but exact state is undetermined. 
FraudLocation$Sampling.Area..where.retail.fish.purchased.[FraudLocation$Sampling.Area..where.retail.fish.purchased.== "USA"] <- "USA (state undetermined)"

FraudLocation$Sampling.Area..where.retail.fish.purchased.[FraudLocation$Sampling.Area..where.retail.fish.purchased.== "US"] <- "USA (state undetermined)"

FraudLocation$Sampling.Area..where.retail.fish.purchased.[FraudLocation$Sampling.Area..where.retail.fish.purchased.== "21 states"] <- "USA (state undetermined)"

FraudLocation$Sampling.Area..where.retail.fish.purchased.[FraudLocation$Sampling.Area..where.retail.fish.purchased.== "United States"] <- "USA (state undetermined)"

FraudLocation$Sampling.Area..where.retail.fish.purchased.[FraudLocation$Sampling.Area..where.retail.fish.purchased.== "medium size city in SE US"] <- "USA (state undetermined)"

#There are some samples that dont have any location mentioned. These are empty strings and I will replace them with NA. 
FraudLocation[FraudLocation == ''] <- NA

#Replace the NA's with an Undetermined Location 
FraudLocation[is.na(FraudLocation)] <- "Undetermined"

#Here I will replace the locations to show the state where the samples were retrieved from 

#New York
FraudLocation[FraudLocation == "NY"] <- "New York"
FraudLocation[FraudLocation == "New York City "] <- "New York"
FraudLocation[FraudLocation == "New York City"] <- "New York"
FraudLocation[FraudLocation == "New Bedford, MA (company)"] <- "New York"
FraudLocation[FraudLocation == "NYC"] <- "New York"
FraudLocation[FraudLocation == "New York, New York"] <- "New York"

#Massachusetts
FraudLocation[FraudLocation == "Boston, MA"] <- "Massachusetts"
FraudLocation[FraudLocation == "MA (company)"] <- "Massachusetts"
FraudLocation[FraudLocation == "MA (company)"] <- "Massachusetts"

#Washington 
FraudLocation[FraudLocation == "W.Washington State"] <- "Washington"
FraudLocation[FraudLocation == "Seattle, WA"] <- "Washington"
FraudLocation[FraudLocation == "Bellingham, WA"] <- "Washington"
FraudLocation[FraudLocation == "Washington, DC "] <- "Washington"
FraudLocation[FraudLocation == "Washington, DC"] <- "Washington"

#California
FraudLocation[FraudLocation == "Los Angeles"] <- "California"
FraudLocation[FraudLocation == "Los Angeles, CA, USA"] <- "California"
FraudLocation[FraudLocation == "California, Los Angeles"] <- "California"
FraudLocation[FraudLocation == "California, San Francisco"] <- "California"
FraudLocation[FraudLocation == "California, Oakland"] <- "California"
FraudLocation[FraudLocation == "California, San Jose"] <- "California"
FraudLocation[FraudLocation == "California, Sausalito"] <- "California"
FraudLocation[FraudLocation == "California, San Rafael"] <- "California"
FraudLocation[FraudLocation == "California, Walnut Creek"] <- "California"
FraudLocation[FraudLocation == "California, Orange County"] <- "California"
FraudLocation[FraudLocation == "Santa Cruz, CA"] <- "California"
FraudLocation[FraudLocation == "San Diego"] <- "California"
FraudLocation[FraudLocation == "Santa Monica, CA (company), CA (purchaser)"] <- "California"
FraudLocation[FraudLocation == "San Francisco, CA"] <- "California"
FraudLocation[FraudLocation == "Sentencing in Los Angeles California"] <- "California"

#Florida 
FraudLocation[FraudLocation == "Florida - Jacksonville area"] <- "Florida"
FraudLocation[FraudLocation == "Tampa, FL"] <- "Florida"
FraudLocation[FraudLocation == "Tampa, St. Petersburg, FL"] <- "Florida"
FraudLocation[FraudLocation == "Panama City, FL"] <- "Florida"
FraudLocation[FraudLocation == "Hialeah, FL"] <- "Florida"
FraudLocation[FraudLocation == "Volusia county, FL"] <- "Florida"
FraudLocation[FraudLocation == "Fort Myers, Florida"] <- "Florida"
FraudLocation[FraudLocation == "Tallahassee, Florida"] <- "Florida"
FraudLocation[FraudLocation == "Tampa Bay, Florida"] <- "Florida"
FraudLocation[FraudLocation == "North Miami Beach, FL"] <- "Florida"
FraudLocation[FraudLocation == "Miami, FL (company)"] <- "Florida"
FraudLocation[FraudLocation == "Tampa, FL (company)"] <- "Florida"
FraudLocation[FraudLocation == "FL (company)"] <- "Florida"
FraudLocation[FraudLocation == "Hialeah, FL (company)"] <- "Florida"
FraudLocation[FraudLocation == "FL (purchaser)"] <- "Florida"

#Missouri 
FraudLocation[FraudLocation == "St. Louis, MO"] <- "Missouri"
FraudLocation[FraudLocation == "Kansas City, MO"] <- "Missouri"

#Georgia
FraudLocation[FraudLocation == "Atlanta, GA"] <- "Georgia"
FraudLocation[FraudLocation == "GA (company)"] <- "Georgia"
FraudLocation[FraudLocation == "Savannah, GA"] <- "Georgia"

#Maryland 
FraudLocation[FraudLocation == "Baltimore, MD"] <- "Maryland"

#Arizona 
FraudLocation[FraudLocation == "Phoenix,AZ"] <- "Arizona"

#Illinois 
FraudLocation[FraudLocation == "Chicago, IL"] <- "Illinois"
FraudLocation[FraudLocation == "Addison, IL (company)"] <- "Illinois"
FraudLocation[FraudLocation == "Oak Park, IL"] <- "Illinois"
FraudLocation[FraudLocation == "Chicago and suburbs"] <- "Illinois"

#North Carolina 
FraudLocation[FraudLocation == "Gastonia, NC"] <- "North Carolina"

#Virginia 
FraudLocation[FraudLocation == "VA (company)"] <- "Virginia"



#Some values have in the Sample Area column mention 2+ states. I am going to repeat those rows by the number of states mentioned and replace the values with each state mentioned.

#Study 1
Study1 <-FraudLocation %>% slice(rep(1,2)) #Replicated 1st study twice
Study1[1,3] <- "USA (state undetermined)"
Study1[2,3] <- "Canada"  

#Study 3
Study3 <- FraudLocation %>% slice(rep(17,8)) #Replicated 3rd study 8 times
Study3[1,3] <-"Delaware"
Study3[2,3]<- "Florida"
Study3[3,3]<- "Illinois"
Study3[4,3]<- "Massachusetts"
Study3[5,3]<- "New York"
Study3[6,3]<- "North Carolina"
Study3[7,3]<- "South Carolina"
Study3[8,3]<- "Wisconsin"  #Each state is now represented in the 3rd study 

#Study 6
#two rows x 5 states = 10 repeats
Study6<-FraudLocation %>% slice(rep(34,10))
#Each two rows will have the same state name out of the 5 states mentioned. 
Study6[1:2, 3]<- "California"
Study6[3:4, 3]<- "New York"
Study6[5:6, 3]<- "North Carolina"
Study6[7:8, 3]<- "Missouri"
Study6[9:10, 3]<- "Florida"

#Study 9
#6 rows x 2 states = 12 repeats
Study9<-FraudLocation %>% slice(rep(59,12))
#I will repeat the same process here. 
Study9[1:6, 3]<-"Colorado"
Study9[7:12, 3]<-"New York"


#Study 10
#3 rows x 2 states = 6 repeats
Study10<-FraudLocation %>% slice(rep(65,6))
Study10[1:3,3]<- "Florida"
Study10[4:6,3]<- "Alabama"

#Study 12
#2 rows x 2 states
Study12<-FraudLocation %>% slice(rep(79,4))
Study12[1:2,3] <-"California"
Study12[3:4,3] <-"Washington"

#Study 17
#4 rows x 10 states
Study17<- FraudLocation %>% slice(rep(166,40))


#Study 18
#14 rows x 3 states 
Study18<- FraudLocation %>% slice(rep(170,42))
 
  
#Study 63
#5 rows x 4 states 
Study63<- FraudLocation %>% slice(rep(234,20))


#Study 100
#5 rows x 2 states 
Study100<- FraudLocation %>% slice(rep(315,10))

#Study 102
#17 rows x 4 states 
Study102<- FraudLocation %>% slice(rep(332,68))


#Study 121
# 401 rows x 10 states 
Study121<- FraudLocation %>% slice(rep(384,4010))


#Study 122
#44 rows x 8 states 
Study122 <- FraudLocation %>% slice(rep(785,352))

#Study 123
# 34 rows x 2 states
Study123<- FraudLocation %>% slice(rep(829,68))

#Study 145
#2 rows x 2 states 
Study145<- FraudLocation %>% slice(rep(866,4))

#Study 147
#10 rows x 3 states
Study147<- FraudLocation %>% slice(rep(870,30))


#Study 150
#1 row x 2 states 
Study150<- FraudLocation %>% slice(rep(887,2))

#Study 151
#1 row x 2 states 
Study151 <- FraudLocation %>% slice(rep(888,2))

#Study 154
#1 row x 3 states
Study154<- FraudLocation %>% slice(rep(896,3))

#Study 160
#1 row x 3 states
Study160<- FraudLocation %>% slice(rep(907,3))

#For the studies that mention 2+ states in a single cell, I am going to remove these rows so then I can Bring them back in in a join function where each cell mentions 1 state as opposed to multiple. I am going to put this into a separate data frame as a test. As to not disturb the original FraudLocation data frame. 


  
  
  
FraudLocation_full_fraud1st <- full_join(FraudLocation, Study1, by= "Study.number")
FraudLocation_full_fraud1st<- select(FraudLocation_full_fraud1st, -Study.authors...year.y, -Sampling.Area..where.retail.fish.purchased..y)


```

